from datetime import date

from app.schemas.ai_outputs import DailyPlanAiOutput
from app.schemas.common import RiskLevel, TaskPriority, TaskStatus
from app.schemas.daily_plan import DailyPlanCreate
from app.schemas.task import Task
from app.services.gemini_service import GeminiService
from app.services.mission_context import MissionContext
from app.services.prompt_loader import PromptLoader


class Scheduler:
    def __init__(
        self,
        gemini_service: GeminiService | None = None,
        prompt_loader: PromptLoader | None = None,
    ) -> None:
        self.gemini_service = gemini_service
        self.prompt_loader = prompt_loader or PromptLoader()

    def generate_daily_plan(self, context: MissionContext) -> DailyPlanAiOutput:
        try:
            prompt = self.prompt_loader.render(
                "scheduler", {"scheduler_input": context.to_ai_snapshot()}
            )
            service = self.gemini_service or GeminiService()
            return service.generate_structured(prompt, DailyPlanAiOutput)
        except Exception:
            return self._fallback_daily_plan(context)

    def build_daily_plan_create(
        self,
        context: MissionContext,
        ai_output: DailyPlanAiOutput,
    ) -> DailyPlanCreate:
        task_ids = self._resolve_task_ids(context.tasks, ai_output.task_titles)
        if not task_ids:
            task_ids = [task.id for task in self._select_tasks_rule_based(context)]

        return DailyPlanCreate(
            mission_id=context.mission.id,
            plan_date=context.today,
            focus=ai_output.focus,
            summary=ai_output.summary,
            task_ids=task_ids,
            estimated_minutes=ai_output.estimated_minutes,
            risk_level=ai_output.risk_level,
            coach_message=ai_output.coach_message,
        )

    def _resolve_task_ids(self, tasks: list[Task], titles: list[str]) -> list[str]:
        title_map = {task.title.lower(): task.id for task in tasks}
        return [title_map[title.lower()] for title in titles if title.lower() in title_map]

    def _select_tasks_rule_based(self, context: MissionContext) -> list[Task]:
        candidates = context.tasks_for_today() or context.overdue_tasks()
        if not candidates:
            candidates = [
                task
                for task in context.tasks
                if task.status in (TaskStatus.PENDING, TaskStatus.IN_PROGRESS)
            ]

        daily_budget = context.mission.available_minutes_per_day or 120
        selected: list[Task] = []
        used_minutes = 0

        priority_order = {
            TaskPriority.CRITICAL: 0,
            TaskPriority.HIGH: 1,
            TaskPriority.MEDIUM: 2,
            TaskPriority.LOW: 3,
        }

        for task in sorted(
            candidates,
            key=lambda t: (priority_order.get(t.priority, 2), t.order_index),
        ):
            minutes = task.estimated_minutes or 30
            if used_minutes + minutes > daily_budget and selected:
                break
            selected.append(task)
            used_minutes += minutes

        return selected[:5]

    def _fallback_daily_plan(self, context: MissionContext) -> DailyPlanAiOutput:
        selected = self._select_tasks_rule_based(context)
        total_minutes = sum(task.estimated_minutes or 30 for task in selected)
        focus = selected[0].title if selected else "Review mission progress"
        summary = (
            f"Focus on {len(selected)} high-leverage tasks today."
            if selected
            else "No scheduled tasks today. Review upcoming milestones."
        )

        overdue = len(context.overdue_tasks())
        risk = RiskLevel.HIGH if overdue > 3 else RiskLevel.MEDIUM if overdue else RiskLevel.LOW

        return DailyPlanAiOutput(
            focus=focus,
            summary=summary,
            task_titles=[task.title for task in selected],
            estimated_minutes=total_minutes,
            risk_level=risk,
            coach_message="Stay consistent. Small daily wins compound.",
            scheduling_notes=["Generated by rule-based scheduler fallback."],
        )
